<?php 
echo memory_get_usage();

$spanish = array( 
	'item_name'              =>  "Nombre" , 
	'item_aportedby'			 => "Autor",
	'item_description'       =>  "Descripcion" , 
	'item_found'          =>  "Se han encontrado items" ,
	'item_notfound'          =>  "No se han encontrado items" , 
	'item_searchbyauthor'    =>  "Buscar item por autor" ,
	'item_baddownload' => "Descarga fallida",
	'item_edititem' => "Editar",
	'item_removeitem' => "Borrar",
	'item_reportitem' => "Reportar Item", 
	'item_whyreport' => "Motivo del Reporte", 
	'item_remove' => "Borrar Item",
	'item_removed' => "Item Borrado",
	
	'cms_send' => "Enviar",
	'cms_badreport' => "Reporte erroneo",
	'cms_reportedsuccesfully' => "Reportado correctamente", 
	'cms_loginclosed' => "Pagina cerrada por mantenimiento",
	'cms_closeall' => "Cerrar el acceso a la pagina",
	'cms_closelogin' => "Cerrar el login",
	'cms_webaccesstext' => "Pagina cerrada por mantenimiento",
	'cms_first' => "Primera",
	'cms_previous' => "Anterior",
	'cms_last' => "Ultima",
	'cms_next' => "Siguiente",
	'cms_delete' => "Borrar", 
	'cms_install' => "Instalar", 
	'cms_dirnotfound' => "Directorio no encontrado", 
	'cms_onlyfriends' => "Solo amigos",
	
	'user_invitationlist' => "Lista de invitados", 
	'user_tips' => "El nombre debe contener entre 4 y 26 caracteres alfanumericos o  _",
	'user_passtips' => "La contraseña debe contener entre 6 y 28 caracteres",
	'user_emailtips' => "El email debe existir y ser valido ya que se mandara un email de confirmacion",
	'user_secretasktips' => "Una pregunta que se te hara para recuperar la contraseña en caso de perderla",
	'user_secretanswertips' => "La respuesta a la anterior pregunta que se te solicitara para recuperar la contraseña",
	
	'user_logsuccess'      =>  "Logueado satisfactoriamente" , 
	'user_register'        =>  "Registrate" , 
	'user_registersuccess' =>  "Registrado satsifactoriamente" , 
	'user_accountbanned' =>  "Usuario baneado" , 
	'user_seefriends' => "Ver amigos",
	
	'user_birthdate' => "Fecha de nacimiento",
	'user_website' => "Pagina web",
	'user_firm' => "Firma",
	
	'user_name'        =>  "Nombre" , 
	'user_newname'     =>  "Nuevo nombre" , 
	'user_renewname'   =>  "Repetir nuevo nombre" , 
	'user_namechanged' =>  "Nombre cambiado" , 
	'user_badname'     =>  "Nombre erroneo" , 
	'user_emptynick'     =>  "Nombre vacio" ,
	'user_nickinuse'     =>  "Nombre en uso" ,
	'user_badnick'     =>  "Nombre invalido, corto o muy largo" ,
	'user_notexists'     =>  "Usuario no existente" ,
	'user_namenotfound'     =>  "Nombre erroneo o inexistente" ,

	'user_pass'         =>  "Contrase&ntilde;a" , 
	'user_repass'       =>  "Repetir contrase&ntilde;a" , 
	'user_newpass'      =>  "Nueva contrase&ntilde;a" , 
	'user_renewpass'    =>  "Repetir nueva contrase&ntilde;a" , 
	'user_oldpass'      =>  "Contrase&ntilde;a anterior" , 
	'user_passchanged'  =>  "Contrase&ntilde;a cambiada" , 
	'user_badpass'      =>  "Contrase&ntilde;a no valida" , 
	'user_badrepeatpass'    =>  "Las contrase&ntilde;as no coinciden" , 
	'user_recpass'      =>  "Recuperar contrase&ntilde;a" , 
	'user_recpassemail' =>  "Hola {USERNAME}.\n Hemos recibido una peticion de cambio de contraseña, por favor para completarla entra en: {URL}",
	'user_emptypass'     =>  "Contraseña vacia" ,
	'user_passnotmatch' =>  "La contraseña no coincide" , 
	'user_passemailsended' => "Se ha enviado a su email las instrucciones para recuperar la contraseña",
	'user_badrecpassform' => "El tiempo (sesion) para caducar la contraseña ha caducado, reintentalo",
	'user_passchsuccess' => "Contraseña cambiada correctamente",

	'user_secretask'           =>  "Pregunta Secreta" , 
	'user_secretanswer'        =>  "Respuesta Secreta" , 
	'user_newsecretask'        =>  "Nueva Pregunta Secreta" , 
	'user_newsecretanswer'     =>  "Nueva Respuesta Secreta" , 
	'user_secretaskchanged'    =>  "Pregunta secreta cambiada" , 
	'user_secretanswerchanged' =>  "Respuesta secreta cambiada" ,
	'user_badsecretask'        =>  "El campo pregunta secreta esta vacio" , 
	'user_emptysecretask'     =>  "Pregunta secreta vacia" ,
	'user_emptysecretanswer'     =>  "Respuesta secreta vacia" ,
	
	'user_email'        =>  "E-Mail" , 
	'user_reemail'      =>  "Repetir E-Mail" , 
	'user_newemail'     =>  "Nuevo E-Mail" , 
	'user_renewemail'   =>  "Repetor nuevo E-Mail" , 
	'user_oldemail'     =>  "E-Mail anterior" , 
	'user_emailchanged' =>  "E-Mail cambiado" , 
	'user_bademail'     =>  "E-Mail no valido" , 
	'user_badrepeatemail'   =>  "Los E-Mail no coinciden" , 
	'user_emptyemail'     =>  "E-Mail vacio" ,
	'user_emailinuse'     =>  "E-Mail en uso" ,
	'user_emailnotexists'     =>  "E-Mail inexistente" ,
	
	'user_avatar'        =>  "Avatar" , 
	'user_newavatar'     =>  "Nuevo avatar" , 
	'user_avatarchanged' =>  "Avatar cambiado" , 
	'user_badavatar'     =>  "Avatar erroneo" , 
	
	'user_style'        =>  "Estilo" , 
	'user_newstyle'     =>  "Nuevo estilo" , 
	'user_stylechanged' =>  "Estilo cambiado" , 
	'user_badstyle'     =>  "Estilo erroneo" , 
	
	'user_sex' => "Sexo",
	'user_nosex' => "Sin sexo",
	'user_man' => "Hombre",
	'user_woman' => "Mujer",
	
	'user_friend'    =>  "Ver amigo",
	'user_notbefriend'    =>  "Eliminar amigo",
	'user_acceptfriend'     =>  "Aceptar amigo" , 
	'user_befriend'     =>  "Ser amigo" , 
	'user_alreadyfriend'     =>  "Ya es amigo" , 
	'user_notfriend'    =>  "No es amigo",
	
	'user_found'          =>  "Usuario encontrado" , 
	'user_notfound'       =>  "Usuario no encontrado" , 
	'user_searchbyemail' =>  "Buscar usuario por email" , 
	'user_memberlist'     =>  "Lista de usuarios" , 
	'user_ucp'            =>  "Panel de Control de Usuario" , 
	'user_logout'         =>  "Salir" , 
	'user_login'          =>  "Entrar" , 
	'user_selectuser'     =>  "Seleccionar usuario" , 
	'user_reputation'     =>  "Reputacion" , 
	'user_edit'           =>  "Editar usuario",
	'user_viewprofile'    =>  "Ver Perfil de Usuario",
	'user_seeaporteditems' => "Items aportados",
	'user_seepostedcomments' => "Comentarios posteados",
	
	'mp_success'  =>  "Enviado satisfactoriamente" , 
	'mp_send'     =>  "Enviar MP" , 
	'mp_receiver' =>  "Recibido por:" , 
	'mp_emitter'  =>  "Enviado por:" , 
	'mp_topic'    =>  "Asunto" , 
	'mp_message'  =>  "Mensaje" , 
	'mp_status'   =>  "Estado" , 
	'mp_inbox'    =>  "Bandeja de entrada" , 
	'mp_outbox'   =>  "Bandeja de Salida" , 
	'mp_new'      =>  "Nuevo MP" , 
	'mp_view'     =>  "Ver MP" , 
	'mp_read'     =>  "MP leido" , 
	'mp_notread'  =>  "MP no leido" , 
	'mp_date'     =>  "Fecha de envio" ,
	'mp_error'     =>  "MP no enviado" , 
	'mp_reply'     =>  "Responder MP" , 
	'mp_email'     =>  "Tienes un mensaje privado",
	'mp_emailtext' =>  "Hola {USERNAME}.\n Has recibido un mensaje privado de %s.\n Entra en {URL} para verlo" , 
	'mp_sendto' => "Enviar a",
	
	'cms_contact'         =>  "Contacta" , 
	'cms_search'          =>  "Buscar" , 
	'cms_footer'          =>  '<a href="http://code.google.com/p/foecms/source/browse/trunk">FoeCMS</a> (CC)2010-2012 Mario Gonzalez. ' , 
	'cms_guestaccess'     =>  "Acceder como invitado" , 
	'cms_guest'           =>  "Invitado",
	'cms_lastuser'        =>  "Hay %s usuarios registrados. El ultimo usuario registrado es %s",
	'cms_sessionremember' =>  "Recordar Sesion" , 
	'cms_returnif'        =>  "Haz click aqui si tu navegador no te redirige",
	'cms_returntologin'   =>  "Volver al login",
	'cms_wellcome'        =>  "Bienvenido a {WEBNAME}",
	'cms_wellcomeEmail'   =>  "Bienvenido {UERNAME} a {WEBNAME}.\nTu contraseña es {PASSWORD}. Para proteger tus datos se almacenara cifrada (en md5) en nuestro servidor.\nEsperamos que disfrutes tu estancia en {WEBNAME}.\n Un saludo, el administrador.",
	'cms_acppanel' => "Panel de admin",
	'cms_cantregister' => "Registros cerrados",
	'cms_delinstall' => "Borre o renombre la carpeta install para poder continuar",
	'cms_searchforname'  =>  "Buscar por nombre" , 
	'cms_index' => "Indice",
	'item_nocomment'      =>  "No comentarios" , 
	'item_alreadyvoted'      =>  "Ya has votado" , 
	
	'acp_returntoindex' => "Volver al CMS",
	'acp_index' => "Panel Principal",
	'acp_item' => "Items",
	'acp_user' => "Usuarios",
	'acp_notice' => "Noticias",
	'acp_category' => "Categorias",
	'acp_editconfig' => "Configuracion",
	'acp_additem' => "Añadir item",
	'acp_edititem' => "Editar items",
	'acp_adduser' => "Añadir usuario",
	'acp_edituser' => "Editar usuarios",
	'acp_addnotice' => "Añadir noticias",
	'acp_editnotice' => "Editar noticias",
	'acp_addcategory' => "Añadir categoria",
	'acp_editcategory' => "Editar categorias",
	'acp_editcomment' => "Editar comentarios",
	'acp_editinvitation' => "Editar invitaciones",
	'acp_notepanel' => "Notas del Admin",
	'acp_emptynotepanel' => "Panel Vacio",
	'acp_masiveemails' => "Emails Masivos",
	'acp_cmsconfig' => "Configuracion del CMS",
	'acp_noticetext' => "Texto de la noticia",
	'acp_webname' => "Nombre de la web",
	'acp_webdesc' => "Descripcion de la web",
	'acp_webkeywords' => "Keywords",
	'acp_contactmail' => "Email de contacto",
	'acp_cookieprefix' => "Prefijo de la cookie",
	'acp_itemperpage' => "Items por pagina",
	'acp_registeremail' => "Texto del email al registrarse",
	'acp_recpassemail' => "Texto del email al solicitar contraseña",
	'acp_mpemail' => "Texto del email al recibir un MP",
	'acp_invitationemail' => "Texto del email al recibir una invitacion",
	'acp_webkeywordsnote' => "Separados por comas",
	'acp_codereplacesemail' => "Puedes enviar informacion personalizada con {USERNAME}, {EMAIL}, {PASSWORD} (Solo en register), {URL} (Obligatorio en recpassemail y invitationemail), {WEBNAME}, {WEBDESC}",
	'acp_permissionsconfig' => "Configurar permisos",
	'acp_guestaccess' => "Acceso de invitados",
	'acp_guestcomment' => "Comentarios de invitados",
	'acp_guestdownload' => "Descargas de invitados",
	'acp_guestvote' => "Votos de invitados",
	'acp_guestpost' => "Post de invitados",
	'acp_guestregister' => "Registro a invitados",
	'acp_guestregisterwithoutinv' => "Registro sin invitaciones",
	'acp_useraccess' => "Acceso a usuarios",
	'acp_usercomment' => "Comentarios de usuarios",
	'acp_userdownload' => "Descargas de usuarios",
	'acp_uservote' => "Votos de usuarios",
	'acp_userpost' => "Post de usuarios",
	'acp_reportitem' => "Gestor de reportes", 
	'acp_seeprofile' => "Ver perfil",
	'acp_seefriends' => "Ver amigos", 
	'acp_webaccess' => "Acceso a la web",
	'acp_seourl' => "URL amigables (SEO)", 
	'acp_webaccesstext' => "Texto de mantenimiento",
	'acp_addtheme' => "Añadir tema", 
	'acp_addlang' => "Añadir traduccion", 
	'acp_deletereport' => "Eliminar reporte", 
	'acp_defaultstyle' => "Estilo por defecto", 
	
	'user_createitem' => "Crear item",
	'user_invtext' => "Esta invitacion se ha enviado al correo {EMAIL} por el usuario {USERNAME}.\n Gracias por unirte a nosotros. {URL}\n",
	'user_invitation' => "Invitacion",
	'user_badinvitation' => "Invitacion erronea o caducada",
	'user_invitationsended' => "Todo correcto!, La invitacion se ha enviado por email",
	'user_emailinvitation' => "Saludos desde {WEBNAME}. \nNuestro miembro {USERNAME} te ha invitado a registrarte en {URL}. \nUnete a nosotros!",
	'user_nosecretask' => "No tienes pregunta secreta.",
	'user_nosecretanswer' => "No tienes pregunta ni respuesta secretas.",
	'user_visitornumber' => "visitas a tu perfil",
	'user_loginclosed' => "Lo sentimos la pagina esta cerrada, por favor vuelve mas tarde",
	'user_level' => "Nivel",
	'user_leveluser' => "Usuario",
	'user_mod' => "Moderador",
	'user_admin' => "Administrador",
	'user_banned' => "Baneado",
	'user_website' => "Pagina web",
	'user_invitationnumber' => "Numero de invitaciones",
	
	'contact_name' => "Nombre y apellidos",
	'contact_succesful' => "Su mensaje a sido enviado correctamente. Gracias por contactar con nosostros",
	'contact_fail' => "Error al enviar el formulario. Por favor, inténtelo de nuevo mas tarde",
	
	'category_name' => "Nombre",
	'category_parent' => "Categoria superior",
	'category_noparent' => "Sin categoria superior",
	
	'item_timesdownloaded' => "Veces descargado",
	'item_category' => "Categoria",
	'item_file' => "Archivo",
	'item_image' => "Imagen",
	'item_comment' => "Comentario",
	'item_removed' => "Item borrado",
	'item_createdsuccessfully' => "Item creado correctamente",
	'item_edited' => "Item editado",
	
	'comment_created' => 'Comentario creado',
	'comment_removed' => "Comentario borrado",
	'comment_number' => "Numero de comentarios",
	'comment_doComment'       =>  "Comentar" ,
	'comment_list'        =>  "Comentarios" , 
	'comment_nocomment'      =>  "Sin comentarios" , 
	
	'cms_styledeleteerror' => "No se puede eliminar el estilo por defecto", 
	'cms_onlyregaccess' => "Solo los Usuarios registrados pueeden ver las portadas.",
	'cms_yes' => "Si",
	'cms_no' => "No",
	'cms'
); 

$language = array (
	'lang' => "es",
	'lang_name' => "Espa&ntilde;ol",
	'lang_from' => "en",
	'lang_array' => $spanish
);
?>
